### ISSUE TITLE
连续调用客户端 close崩溃

### ISSUE THREAD

**Issue by chenzl-123** [qicosmos/rest_rpc#111]
代码段：
#include <iostream>
#include "rest_rpc.hpp"
using namespace rest_rpc;
int test() {
	rpc_client client("127.0.0.1", 9110);
	client.enable_auto_reconnect(); //automatic reconnect
	client.enable_auto_heartbeat();
	if (!client.connect(30)) {
		printf("%s:connect error\r\n", __FUNCTION__);
		return -1;
	}
	try {
		bool bServerStat = false;
		if (false == client.has_connected()) {
			printf("%s:client is not connected\r\n", __FUNCTION__);
			return -2;
		}
		auto result = client.async_call<FUTURE>("getServerStat");
		if (result.wait_for(std::chrono::seconds(5)) == std::future_status::timeout) {
			return -3;
		}
		bServerStat = result.get().as<bool>();
	}
	catch (const std::exception& ex) {
		printf("%s:call timeout, error message:%s\r\n", __FUNCTION__, ex.what());
		return -4;
	}
	return 0;
}

int main(int argc, char *argv[]) {
	
	for (int nI = 0; nI < 100; nI++) {
		printf("111111111111111\r\n");
		test();
		printf("222222222222222\r\n");
	}
	printf("success\r\n");
    return 0;
}

**Comment by chenzl-123** [comment]
![image](https://github.com/qicosmos/rest_rpc/assets/58251912/7bdd2d00-c2b4-47fe-b604-fe204c11e300)

**Comment by qicosmos** [comment]
已经fix了，请拉最新代码验证一下。
