### ISSUE TITLE
编译时msgpack报大量错误

### ISSUE THREAD

**Issue by LeoYang06** [qicosmos/rest_rpc#14]
#### C++新手，rest_rpc适用于windows么？
配置了第三方 (non-Boost) Asio、msgpack附加包含，编译时（Visual Studio 2019 (v142)、Debug、Win32）msgpack报大量错误，是配置原因么，毫无头绪，请各位大大指教。
[错误信息下载](https://ws28.cn/f/38mv02truql)。

**Comment by qicosmos** [comment]
先把example里面的例子运行起来。

**Comment by LeoYang06** [comment]
> 先把example里面的例子运行起来。

example编译运行成功。但我的示例是MFC工程，msgpack似乎在"MFC shared dll"下无法编译通过，[这里有一些讨论](https://stackoverflow.com/questions/5469230/messagepack-fast-cross-platform-serializer-and-rpc-please-share-experience)，我不确定是不是这个原因。

**Comment by qicosmos** [comment]
msgpack应该是没问题的，建议你单独用mfc工程测试一下msgpack

**Comment by LeoYang06** [comment]
> msgpack应该是没问题的，建议你单独用mfc工程测试一下msgpack

谢谢，我重新建的MFC工程rest_rpc终于运行起来了，应该和我原工程配置环境有关吧，原因未知。

**Comment by asing325** [comment]
vs2017， msgpack 用最新的 V3版本，编译错误
\codec.h(38): error C2665: “msgpack::v3::unpack”: 12 个重载中没有一个可以转换所有参数类型

修改 好了, 增加v1:: 
  struct msgpack_codec {
...
  template<typename T>
  T unpack(char const* data, size_t length) {
    try {
      msgpack::v1::unpack(&msg_, data, length);
      return msg_.get().as<T>();
    } catch (...) { throw std::invalid_argument("unpack failed: Args not match!"); }
  }

 private:
     msgpack::v1::unpacked msg_;
  };
