### ISSUE TITLE
是否支持引用方式传参？

### ISSUE THREAD

**Issue by shfxxer** [qicosmos/rest_rpc#147]
类似如下：

//client
std::string info
client.call<int>("get_info",info)
//info 内容为"hello"，并且正常返回info.len

//server
int get_info(std::string & info)
{
    info = "hello";
    return info.length();
}

非常感谢！

**Comment by qicosmos** [comment]
有例子：https://github.com/qicosmos/rest_rpc/blob/master/examples/server/main.cpp#L29

支持传常量左值引用参数。
