### ISSUE TITLE
麻烦问一下该库怎么上传下载大的文件

### ISSUE THREAD

**Issue by baihejing** [qicosmos/rest_rpc#41]

**Comment by leielyq** [comment]
@baihejing  请问怎么解决大文件上传

**Comment by qicosmos** [comment]
上传大文件也很简单，你可以增加一个rpc服务，里面的参数有总长度和当前长度，当你发现累计收到的长度达到总长度的时候就走上传完成的逻辑，否则不断追加上传的内容。我后面抽空加一个这样的例子。
