### ISSUE TITLE
The flow chart of rpc_client and rpc_server

### ISSUE THREAD

**Issue by yangtsecxf** [qicosmos/rest_rpc#47]
![rest_rpc_flow](https://user-images.githubusercontent.com/5189212/120488210-288c1f00-c3e9-11eb-875a-a08f98cc3c9d.jpg)

**Comment by yangtsecxf** [comment]
为了更好理解源码，画了rpc_client和rpc_server的flow chart，不当之处，还请指教。

**Comment by qicosmos** [comment]
比较清晰，挺不错。

**Comment by qicosmos** [comment]
希望你能参与维护rest_rpc，可以加项目qq群：340713904

**Comment by yangtsecxf** [comment]
好的，我也希望参加rest_rpc或者cinatra的维护工作，准备在公司引入相关的技术。

**Comment by yangtsecxf** [comment]
画了flow-chart才发现rest_rpc的
连接-认证
请求-路由-应答
订阅-广播
这几条主线的脉络非常清晰，有了这些，很多场景都够用了。👍
