### ISSUE TITLE
server 如何优雅的退出？

### ISSUE THREAD

**Issue by zh1an** [qicosmos/rest_rpc#51]
我用的平台是 Windows，编译器使用的是 MSVC 2015，并且将该程序嵌入到了 QT 的程序中。并且我的程序被编译成了后台程序，没办法接收信号量。在这种情况下，如何优雅地退出服务器呢？

**Comment by zh1an** [comment]
对了，为了不阻塞 QT 的主线程，我使用的是 async_run 接口。

**Comment by qicosmos** [comment]
把它通过智能指针创建，需要推出的时候直接把这个智能指针设置为nullptr即可。
