### ISSUE TITLE
客户端先启动，然后再启动服务端，不能自动重连

### ISSUE THREAD

**Issue by pzhu10** [qicosmos/rest_rpc#55]
客户端先启动，然后再启动服务端，不能自动重连
作者大神，请问有没有QQ群可以交流一下，我测试发现好多问题

**Comment by qicosmos** [comment]
qq群 340713904

**Comment by qicosmos** [comment]
有专门的测试重连的例子:https://github.com/qicosmos/rest_rpc/blob/master/examples/client/main.cpp#L301
可以先启动client，再启动server，是可以连接上的，检查一下你的用法和例子里是不是不一样。

另外还有哪些问题请发出来。

**Comment by qicosmos** [comment]
有专门的测试重连的例子:https://github.com/qicosmos/rest_rpc/blob/master/examples/client/main.cpp#L301
可以先启动client，再启动server，是可以连接上的，检查一下你的用法和例子里是不是不一样。

另外还有哪些问题请发出来。

**Comment by pzhu10** [comment]
> 有专门的测试重连的例子:https://github.com/qicosmos/rest_rpc/blob/master/examples/client/main.cpp#L301 可以先启动client，再启动server，是可以连接上的，检查一下你的用法和例子里是不是不一样。
> 
> 另外还有哪些问题请发出来。

好的，感谢大神的无私开源，之前我发现的问题是因为和我工程里用的boost库版本不一致引起的，换成一致的boost库版本即可正常运行，现在在大规模测试使用，有问题会及时反馈的~~~

**Comment by qicosmos** [comment]
最新版已经去掉了boost依赖了。

**Comment by pzhu10** [comment]
> 最新版已经去掉了boost依赖了。

好啊，我下载最新版本测试一下~~

**Comment by pzhu10** [comment]
谢谢 @qicosmos
