### ISSUE TITLE
当客户端离线时，get_token_list()还是可以获取离线客户端的token

### ISSUE THREAD

**Issue by leielyq** [qicosmos/rest_rpc#67]
可以只获取在线的客户端token吗？

**Comment by qicosmos** [comment]
可以的，这两天看看是什么情况。

**Comment by leielyq** [comment]
谢谢

**Comment by qicosmos** [comment]
增加了清理tokenlist的功能。，你看一下：
https://github.com/qicosmos/rest_rpc/commit/b3554ece770a580c5f20741a634003bfd01350e6

**Comment by leielyq** [comment]
牛啊
